server:
  port: 10235
  servlet:
    context-path: /liu

spring:
  datasource:
    url: jdbc:mysql://rm-2ze3ab5f9bgcbx9m10o.mysql.rds.aliyuncs.com:3306/webscoket?characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
    username: liu
    password: 03145215LL
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#redis配置
  session:
    store-type: redis
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        min-idle: 10000
    timeout: 30000

mybatis-plus:
  mapper-locations: classpath:mapper/*/*Mapper.xml
  global-config:
    db-config:
      id-type: id_worker_str
      #      表前缀
      #      tablePrefix: t_
      #      逻辑删除值
      logic-delete-field: dataStatus  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#      自动刷新mapper.xml 但是需要添加配置文件
#      refresh-mapper: true
